% NeuroProlog neurocode — source: examples/fibonacci.pl
%
% Generated by NeuroProlog Stage 16 Code Generator.
% This file is valid Prolog — load with consult/1.
% Do not add binary or opaque representations.
%
% == Memoisation ==
%   The fib/2 predicate uses an explicit inline cache-check pattern.
%   npl_memo_cache/3 must be declared dynamic before loading this file.
%   The cache stores ground key-result pairs as npl_memo_cache(Key, det, true).
%
% == Source links ==
%   Original source: examples/fibonacci.pl
%   Cognitive marker: none
%   Recursion class:  linear

:- module(fibonacci_nc, [fib/2]).

%% Inline memo cache — declared dynamic to support npl_memo_cache/3 usage.
:- dynamic npl_memo_cache/3.

%% fib/2 — base case: fib(0, 0)
%% source: pos(7,1)  file: examples/fibonacci.pl
%% [memo_site] memoisation enabled for this clause
fib(0, 0) :-
    ( ground(fib(0, 0)) ->
        ( npl_memo_cache(fib(0, 0), det, true) -> true
        ; true,
          assertz(npl_memo_cache(fib(0, 0), det, true)) )
    ; true ).

%% fib/2 — base case: fib(1, 1)
%% source: pos(8,1)  file: examples/fibonacci.pl
%% [memo_site] memoisation enabled for this clause
fib(1, 1) :-
    ( ground(fib(1, 1)) ->
        ( npl_memo_cache(fib(1, 1), det, true) -> true
        ; true,
          assertz(npl_memo_cache(fib(1, 1), det, true)) )
    ; true ).

%% fib/2 — recursive case: fib(N, F)
%% source: pos(9,1)  file: examples/fibonacci.pl
%% recursion: linear
%% [memo_site] memoisation enabled for this clause
fib(N, F) :-
    ( ground(fib(N, F)) ->
        ( npl_memo_cache(fib(N, F), det, true) -> true
        ;   N > 1,
            N1 is N - 1,
            N2 is N - 2,
            fib(N1, F1),
            fib(N2, F2),
            F is F1 + F2,
            assertz(npl_memo_cache(fib(N, F), det, true)) )
    ;   N > 1,
        N1 is N - 1,
        N2 is N - 2,
        fib(N1, F1),
        fib(N2, F2),
        F is F1 + F2 ).
