% NeuroProlog neurocode — source: examples/lists.pl
%
% Generated by NeuroProlog Stage 16 Code Generator.
% This file is valid Prolog — load with consult/1.
% Do not add binary or opaque representations.
%

%% demo_lists/0
%  file: examples/lists.pl

demo_lists :-
    npl_append([1, 2, 3], [4, 5, 6], A),
    write('append: '),
    write(A),
    nl,
    npl_length(A, B),
    write('length: '),
    write(B),
    nl,
    npl_reverse(A, C),
    write('reverse: '),
    write(C),
    nl,
    npl_sum_list(A, D),
    write('sum: '),
    write(D),
    nl.

